version: "3.9"
services:

    rabbitmq:
        image: rabbitmq
        container_name: rabbitmq
        restart: unless-stopped
            
    backend:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: backend
        restart: unless-stopped
        depends_on:
            - rabbitmq
        ports:
            - "127.0.0.1:5000:5000"
        volumes:
            - .:/home/backend/app
        environment:
            APP_SETTINGS: src.config.DevelopmentConfig
            MONGO_URI: "mongodb://mongo/test"
            CELERY_BROKER_URL: "amqp://rabbitmq"
