version: "3.9"
services:

    rabbitmq:
        image: rabbitmq
        container_name: rabbitmq
        restart: unless-stopped

    mongo:
        image: cassandra
        container_name: cassandra
        restart: unless-stopped
        ports:
            - "127.0.0.1:7000:7000"
        volumes:
            - cassy-data:/var/lib/cassandra
            
    backend:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: backend
        restart: unless-stopped
        depends_on:
            - mongo
            - rabbitmq
        ports:
            - "127.0.0.1:5000:5000"
        volumes:
            - .:/home/backend/app
        environment:
            APP_SETTINGS: src.config.DevelopmentConfig
            MONGO_URI: "mongodb://mongo/test"
            CELERY_BROKER_URL: "amqp://rabbitmq"
            
volumes:
    cassy-data:            
